# -*- coding: utf-8 -*-
"""record data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ejgcHkmlToRWCdkqBUocSqVXiisa6sY
"""

win_counts.plot(kind='bar')
plt.title('Win/Loss/Draw Counts')
plt.xlabel('Result')
plt.ylabel('Counts')
plt.show()